// components/app/briefing-view.tsx
"use client"

import { useState } from "react"
import { 
  CURRENT_LOCATION, 
  ORBIT_LOCATIONS,
  type LocationData
} from "@/lib/raven-data"
import { 
  TrendingUp, 
  TrendingDown, 
  MapPin,
  ChevronDown,
  ExternalLink,
  Check
} from "lucide-react"

// ============================================
// LOCATION SELECTOR (Dropdown, not sidebar)
// ============================================
function LocationSelector({ 
  locations,
  selectedId,
  onSelect 
}: { 
  locations: LocationData[]
  selectedId: string
  onSelect: (id: string) => void
}) {
  const [open, setOpen] = useState(false)
  const selected = locations.find(l => l.id === selectedId) || locations[0]

  return (
    <div className="relative">
      <button 
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 font-mono text-xs uppercase tracking-wider text-muted-foreground hover:text-foreground transition-colors"
      >
        <MapPin className="w-3.5 h-3.5 text-accent" />
        <span>{selected.name}</span>
        {selected.label && (
          <>
            <span className="text-border">—</span>
            <span className="text-muted-foreground/60">{selected.label}</span>
          </>
        )}
        <ChevronDown className={`w-3.5 h-3.5 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      
      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute top-full left-0 mt-2 z-50 bg-card border border-border shadow-lg min-w-[240px]">
            {locations.map((loc) => (
              <button
                key={loc.id}
                onClick={() => { onSelect(loc.id); setOpen(false) }}
                className="w-full flex items-center justify-between gap-4 px-4 py-3 hover:bg-accent/5 transition-colors text-left"
              >
                <div>
                  <p className="font-mono text-sm text-foreground">{loc.name}</p>
                  {loc.label && (
                    <p className="font-mono text-[10px] text-muted-foreground uppercase tracking-wider">{loc.label}</p>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  <span className="font-mono text-xs text-muted-foreground">{loc.stabilityScore}</span>
                  {loc.id === selectedId && <Check className="w-3.5 h-3.5 text-accent" />}
                </div>
              </button>
            ))}
            <div className="border-t border-border">
              <button className="w-full px-4 py-3 font-mono text-[10px] uppercase tracking-wider text-accent hover:bg-accent/5 transition-colors text-left">
                + Add Location
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  )
}

// ============================================
// RAVEN BRIEF HEADER - The Primary Narrative
// ============================================
function BriefHeader({ location }: { location: LocationData }) {
  const trendText = location.trend === "improving" 
    ? "improving" 
    : location.trend === "declining" 
    ? "elevated"
    : "stable"
    
  const TrendIcon = location.trend === "improving" 
    ? TrendingUp 
    : location.trend === "declining"
    ? TrendingDown
    : null

  // This would be generated by Claude in production
  const briefNarrative = `Activity in ${location.name} remains ${trendText} this week. Property incidents are concentrated overnight in the downtown corridor — a pattern now in its third week. Infrastructure disruptions on Route 14 continue through Friday. No significant civic changes pending.`

  return (
    <header className="mb-12">
      {/* Brief marker */}
      <div className="flex items-center gap-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-accent">
          Raven Brief
        </span>
        <span className="text-border">—</span>
        <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
          {new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}
        </span>
      </div>

      {/* Primary narrative */}
      <p className="font-mono text-base md:text-lg text-foreground/90 leading-relaxed max-w-2xl">
        {briefNarrative}
      </p>

      {/* Score as supporting evidence */}
      <div className="flex items-center gap-4 mt-6 pt-6 border-t border-border/40">
        <div className="flex items-center gap-2">
          <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
            Stability Index
          </span>
          <span className="font-mono text-sm font-medium text-foreground">
            {location.stabilityScore}
          </span>
        </div>
        {TrendIcon && (
          <div className={`flex items-center gap-1.5 ${
            location.trend === "improving" ? "text-emerald-600" : "text-rose-600"
          }`}>
            <TrendIcon className="w-3.5 h-3.5" />
            <span className="font-mono text-[10px] uppercase tracking-wider">
              {location.trendPercent > 0 ? "+" : ""}{location.trendPercent}% vs last week
            </span>
          </div>
        )}
      </div>
    </header>
  )
}

// ============================================
// INTELLIGENCE MODULE: Emerging Pattern
// ============================================
function EmergingPatternModule() {
  // Only render if there's an active pattern
  const hasPattern = true // Would be conditional in production

  if (!hasPattern) return null

  return (
    <article className="relative border border-accent/30 bg-accent/5 p-6 md:p-8 mb-6">
      {/* Corner accent */}
      <div className="absolute top-0 right-0 w-12 h-12">
        <div className="absolute top-0 right-0 w-full h-[2px] bg-accent" />
        <div className="absolute top-0 right-0 w-[2px] h-full bg-accent" />
      </div>

      <div className="flex items-center gap-3 mb-4">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-accent">
          Emerging Pattern
        </span>
        <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
          Raven Analysis
        </span>
      </div>

      <h3 className="font-[family-name:var(--font-bebas)] text-2xl md:text-3xl tracking-tight text-foreground mb-3">
        Vehicle Break-ins — Downtown Corridor
      </h3>

      <div className="flex flex-wrap items-center gap-x-6 gap-y-2 mb-4">
        <span className="font-mono text-xs text-rose-600">↑ 23% over 3 weeks</span>
        <span className="font-mono text-xs text-muted-foreground">Concentrated 11pm – 3am</span>
        <span className="font-mono text-xs text-muted-foreground">Main St parking lots</span>
      </div>

      <p className="font-mono text-sm text-foreground/80 leading-relaxed max-w-xl">
        <span className="text-foreground font-medium">What it means:</span> Avoid leaving valuables visible in vehicles parked overnight near downtown. Crystal Lake PD has increased patrols in response.
      </p>
    </article>
  )
}

// ============================================
// INTELLIGENCE MODULE: Active Conditions
// ============================================
function ActiveConditionsModule() {
  const conditions = [
    {
      type: "Infrastructure",
      title: "Route 14 Eastbound Closure",
      detail: "Water main repair between Pingree Rd and Main St",
      timeline: "Through Friday",
      impact: "Expect 15-20 min delays during rush hour"
    },
    {
      type: "Infrastructure", 
      title: "Street Light Outage — Walkup Ave",
      detail: "ComEd dispatched for repair",
      timeline: "Est. tomorrow evening",
      impact: null
    }
  ]

  if (conditions.length === 0) return null

  return (
    <article className="border border-border/40 p-6 md:p-8 mb-6">
      <div className="flex items-center gap-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-amber-600">
          Active Conditions
        </span>
        <span className="font-mono text-[10px] text-muted-foreground">
          {conditions.length} disruption{conditions.length !== 1 ? "s" : ""}
        </span>
      </div>

      <div className="space-y-6">
        {conditions.map((condition, i) => (
          <div key={i} className={i > 0 ? "pt-6 border-t border-border/40" : ""}>
            <div className="flex items-start justify-between gap-4 mb-2">
              <h4 className="font-mono text-sm font-medium text-foreground">
                {condition.title}
              </h4>
              <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground whitespace-nowrap">
                {condition.timeline}
              </span>
            </div>
            <p className="font-mono text-xs text-muted-foreground">
              {condition.detail}
            </p>
            {condition.impact && (
              <p className="font-mono text-xs text-foreground/70 mt-2">
                {condition.impact}
              </p>
            )}
          </div>
        ))}
      </div>
    </article>
  )
}

// ============================================
// INTELLIGENCE MODULE: Civic Signals
// ============================================
function CivicSignalsModule() {
  const signals = [
    {
      title: "B-2 Commercial Rezoning Approved",
      implication: "Retail expansion likely on Virginia St corridor. Property assessments may adjust.",
      date: "Effective Feb 15",
      source: "Planning Commission"
    },
    {
      title: "Mixed-Use Development Permit Filed",
      implication: "150 residential units + ground floor retail proposed at former hardware store site.",
      date: "Public hearing Mar 5",
      source: "City Clerk"
    }
  ]

  return (
    <article className="border border-border/40 p-6 md:p-8 mb-6">
      <div className="flex items-center gap-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-sky-600">
          Civic Signals
        </span>
      </div>

      <div className="space-y-6">
        {signals.map((signal, i) => (
          <div key={i} className={i > 0 ? "pt-6 border-t border-border/40" : ""}>
            <div className="flex items-start justify-between gap-4 mb-2">
              <h4 className="font-mono text-sm font-medium text-foreground">
                {signal.title}
              </h4>
              <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground whitespace-nowrap">
                {signal.date}
              </span>
            </div>
            <p className="font-mono text-xs text-foreground/70 leading-relaxed">
              {signal.implication}
            </p>
            <p className="font-mono text-[10px] text-muted-foreground mt-2">
              Source: {signal.source}
            </p>
          </div>
        ))}
      </div>

      <button className="flex items-center gap-2 mt-6 pt-4 border-t border-border/40 font-mono text-[10px] uppercase tracking-wider text-accent hover:text-accent/80 transition-colors">
        View all civic activity
        <ExternalLink className="w-3 h-3" />
      </button>
    </article>
  )
}

// ============================================
// INTELLIGENCE MODULE: What's Quiet
// ============================================
function WhatsQuietModule() {
  const quietAreas = [
    "Violent crime remains at historic lows",
    "Residential areas stable — no notable patterns",
    "School zones clear of incidents this week",
    "No pending tax district changes"
  ]

  return (
    <article className="border border-border/40 p-6 md:p-8 mb-6 bg-card/50">
      <div className="flex items-center gap-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-emerald-600">
          What's Quiet
        </span>
      </div>

      <ul className="space-y-3">
        {quietAreas.map((item, i) => (
          <li key={i} className="flex items-start gap-3">
            <span className="font-mono text-[10px] text-emerald-600 mt-1">✓</span>
            <span className="font-mono text-sm text-foreground/70">{item}</span>
          </li>
        ))}
      </ul>
    </article>
  )
}

// ============================================
// INTELLIGENCE MODULE: Activity Windows
// ============================================
function ActivityWindowsModule() {
  return (
    <article className="border border-border/40 p-6 md:p-8 mb-6">
      <div className="flex items-center gap-3 mb-6">
        <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-muted-foreground">
          Temporal Patterns
        </span>
      </div>

      <div className="space-y-4">
        <div>
          <div className="flex items-center justify-between mb-1">
            <span className="font-mono text-sm text-foreground">Higher Activity Window</span>
            <span className="font-mono text-sm font-medium text-foreground">11PM – 2AM</span>
          </div>
          <p className="font-mono text-xs text-muted-foreground">
            Typical for downtown corridor. Property incidents cluster here.
          </p>
        </div>

        <div className="h-px bg-border/40" />

        <div>
          <div className="flex items-center justify-between mb-1">
            <span className="font-mono text-sm text-foreground">Rush Hour Impact</span>
            <span className="font-mono text-sm font-medium text-amber-600">5PM – 7PM</span>
          </div>
          <p className="font-mono text-xs text-muted-foreground">
            Route 14 closure adding 15-20 min to eastbound commutes.
          </p>
        </div>

        <div className="h-px bg-border/40" />

        <div>
          <div className="flex items-center justify-between mb-1">
            <span className="font-mono text-sm text-foreground">Quietest Period</span>
            <span className="font-mono text-sm font-medium text-emerald-600">3AM – 7AM</span>
          </div>
          <p className="font-mono text-xs text-muted-foreground">
            Consistently low activity across all categories.
          </p>
        </div>
      </div>
    </article>
  )
}

// ============================================
// MAP LINK (Minimal)
// ============================================
function MapLink({ onNavigateToMap }: { onNavigateToMap: () => void }) {
  return (
    <button 
      onClick={onNavigateToMap}
      className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-wider text-muted-foreground hover:text-foreground transition-colors"
    >
      <span>View activity map</span>
      <ExternalLink className="w-3 h-3" />
    </button>
  )
}

// ============================================
// MAIN BRIEFING VIEW
// ============================================
export function BriefingView({ onNavigateToMap }: { onNavigateToMap: () => void }) {
  const [selectedLocationId, setSelectedLocationId] = useState("crystal-lake")
  const selectedLocation = ORBIT_LOCATIONS.find(l => l.id === selectedLocationId) || CURRENT_LOCATION

  return (
    <div className="min-h-screen bg-background">
      {/* Top bar */}
      <div className="border-b border-border/40">
        <div className="flex items-center justify-between px-6 md:px-12 lg:px-28 py-4">
          <div className="flex items-center gap-3">
            <span className="font-mono text-[10px] uppercase tracking-[0.3em] text-accent">
              Raven
            </span>
          </div>
          <div className="flex items-center gap-6">
            <LocationSelector 
              locations={ORBIT_LOCATIONS}
              selectedId={selectedLocationId}
              onSelect={setSelectedLocationId}
            />
            <MapLink onNavigateToMap={onNavigateToMap} />
          </div>
        </div>
      </div>

      {/* Main content */}
      <main className="px-6 md:px-12 lg:px-28 py-12 md:py-16">
        <div className="max-w-3xl">
          {/* Brief header with narrative */}
          <BriefHeader location={selectedLocation} />

          {/* Intelligence modules */}
          <EmergingPatternModule />
          <ActiveConditionsModule />
          <CivicSignalsModule />
          <WhatsQuietModule />
          <ActivityWindowsModule />
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border/40 px-6 md:px-12 lg:px-28 py-6">
        <div className="flex items-center justify-between">
          <span className="font-mono text-[10px] text-muted-foreground">
            Last updated 5 minutes ago
          </span>
          <span className="font-mono text-[10px] text-muted-foreground">
            Data sources: Crystal Lake PD, McHenry County, 311
          </span>
        </div>
      </footer>
    </div>
  )
}
