// lib/mock-data.ts

export const MOCK_INCIDENTS = [
  {
    id: "1",
    type: "crime" as const,
    title: "Vehicle Break-ins Reported on Main Street",
    summary: "3 vehicles broken into overnight in the Main St parking lot between 11pm-3am. Police are investigating and have increased overnight patrols in the area.",
    location: "Main St & Oak Ave",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    urgency: 8,
    coordinates: { lat: 42.2411, lng: -88.3162 },
    source: "Crystal Lake PD",
    verified: true,
    engagement: { comments: 12, shares: 4 },
  },
  {
    id: "2", 
    type: "civic" as const,
    title: "Rezoning Hearing Scheduled for Virginia Street",
    summary: "Public hearing on proposed B-2 commercial rezoning for 450 Virginia St. Property owners within 500ft may see tax reassessment. Comment period open until Feb 15.",
    location: "450 Virginia St",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    urgency: 4,
    coordinates: { lat: 42.2431, lng: -88.3201 },
    source: "Planning Commission",
    verified: true,
    engagement: { comments: 8, shares: 2 },
  },
  {
    id: "3",
    type: "infrastructure" as const,
    title: "Route 14 Eastbound Lanes Closed for Utility Work",
    summary: "Eastbound lanes closed between Pingree Rd and Main St for emergency water main repair. Expect significant delays through Friday. Use Route 176 as alternate.",
    location: "Route 14 at Pingree Rd",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    urgency: 5,
    coordinates: { lat: 42.2251, lng: -88.3102 },
    source: "IDOT",
    verified: true,
    engagement: { comments: 23, shares: 15 },
  },
  {
    id: "4",
    type: "crime" as const,
    title: "Package Theft Pattern Identified on Dole Ave",
    summary: "Multiple package thefts reported this week, primarily targeting deliveries between 2-5pm. Residents advised to use delivery lockers or require signatures.",
    location: "Dole Ave",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    urgency: 6,
    coordinates: { lat: 42.2381, lng: -88.3142 },
    source: "Neighbor Verified",
    verified: false,
    engagement: { comments: 31, shares: 8 },
  },
  {
    id: "5",
    type: "civic" as const,
    title: "New Restaurant Liquor License Application Filed",
    summary: "Application filed for full liquor license at former hardware store location. Proposed hours until 12am weekdays, 2am weekends. City Council vote scheduled Feb 20.",
    location: "123 Williams St",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    urgency: 2,
    coordinates: { lat: 42.2421, lng: -88.3122 },
    source: "City Clerk",
    verified: true,
    engagement: { comments: 45, shares: 12 },
  },
  {
    id: "6",
    type: "crime" as const,
    title: "DUI Checkpoint Planned for Saturday Night",
    summary: "Crystal Lake PD announces sobriety checkpoint on Route 14 near downtown from 10pm-2am Saturday. Part of statewide holiday enforcement campaign.",
    location: "Route 14 Downtown",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    urgency: 3,
    coordinates: { lat: 42.2401, lng: -88.3182 },
    source: "Crystal Lake PD",
    verified: true,
    engagement: { comments: 67, shares: 89 },
  },
  {
    id: "7",
    type: "infrastructure" as const,
    title: "Street Light Outage on Walkup Ave",
    summary: "Multiple street lights reported out along Walkup Ave from Terra Cotta to McHenry Ave. ComEd dispatched for repair, expected restoration by tomorrow evening.",
    location: "Walkup Ave",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    urgency: 4,
    coordinates: { lat: 42.2391, lng: -88.3212 },
    source: "311 Report",
    verified: true,
    engagement: { comments: 5, shares: 2 },
  },
  {
    id: "8",
    type: "civic" as const,
    title: "School Board Meeting: Budget Discussion",
    summary: "District 47 School Board to discuss proposed 2026 budget including potential staff additions and facility improvements. Public comment period at 7pm.",
    location: "District 47 Admin Building",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    urgency: 3,
    coordinates: { lat: 42.2451, lng: -88.3172 },
    source: "D47 Schools",
    verified: true,
    engagement: { comments: 19, shares: 7 },
  },
  {
    id: "9",
    type: "crime" as const,
    title: "Suspicious Activity Reported Near Elementary School",
    summary: "Unknown individual photographing students during recess reported to police. Individual left before officers arrived. No contact made with children. Investigation ongoing.",
    location: "Husmann Elementary",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    urgency: 9,
    coordinates: { lat: 42.2441, lng: -88.3092 },
    source: "Crystal Lake PD",
    verified: true,
    engagement: { comments: 156, shares: 203 },
  },
  {
    id: "10",
    type: "infrastructure" as const,
    title: "Water Main Flushing Schedule Released",
    summary: "Annual hydrant flushing begins next week. Temporary water discoloration possible. Run cold water for 5 mins if affected. Full schedule posted on city website.",
    location: "Citywide",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    urgency: 2,
    coordinates: { lat: 42.2411, lng: -88.3162 },
    source: "Public Works",
    verified: true,
    engagement: { comments: 8, shares: 14 },
  },
  {
    id: "11",
    type: "civic" as const,
    title: "Downtown Parking Changes Take Effect Monday",
    summary: "New 2-hour parking limits on Williams St between Woodstock and Virginia. Permits available for downtown employees. Meters replaced with mobile payment zones.",
    location: "Downtown",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    urgency: 3,
    coordinates: { lat: 42.2418, lng: -88.3168 },
    source: "City Hall",
    verified: true,
    engagement: { comments: 92, shares: 31 },
  },
  {
    id: "12",
    type: "crime" as const,
    title: "Catalytic Converter Thefts Continue",
    summary: "Two more catalytic converter thefts reported overnight. Toyota Prius and Honda CRV targeted. Residents urged to park in well-lit areas and consider anti-theft devices.",
    location: "Lake Shore Dr",
    municipality: "Crystal Lake",
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    urgency: 6,
    coordinates: { lat: 42.2371, lng: -88.3232 },
    source: "Crystal Lake PD",
    verified: true,
    engagement: { comments: 44, shares: 28 },
  },
]

export type Incident = typeof MOCK_INCIDENTS[0]

export type ViewType = "pulse" | "map" | "forecast" | "alerts" | "watchlist" | "profile"